all: e1 e2 e3 e4

e1: example1.cc
	g++ -o e1 example1.cc

e2: example2.cc
	g++ -o e2 example2.cc

e3: example3.cc
	g++ -o e3 example3.cc

e4: example4.cc
	g++ -o e4 example4.cc

clean:
	rm -f e1 e2 e3 e4